server:
  port: "8080"
  host: "0.0.0.0"
  mode: "development"
  read_timeout: 10  # seconds
  write_timeout: 10 # seconds

db:
  host: "localhost"
  port: "8529"
  user: "root"
  password: "Arshio12*"
  dbname: "starnet"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
  max_retries: 3
  pool_size: 100
  min_idle_conns: 10

jwt:
  secret: "your-super-secret-key-should-be-at-least-32-chars"
  expire_hour: 24
  refresh_expire_day: 7

log_level: "info"
